// Dictionary of items.
const ITEMS = [
    {code : 'BAN1', description : 'BANAK 1"'},
    {code : 'BAN1B', description :  'BANAK 1 1/2"'},
    {code : 'BAN2', description : 'BANAK 2"'},
    {code : 'CAB1', description : 'CAOBA BLANCA 1"'},
    {code : 'CAB1B', description :  'CAOBA BLANCA 1 1/2'},
    {code : 'CAB2', description : 'CAOBA BLANCA 2"'},
    {code : 'POP1', description : 'POPLAR 1"'},
    {code : 'POP1B', description :  'POPLAR 1 1/2'},
    {code : 'POP2', description : 'POPLAR 2"'},
    {code : 'REG1', description : 'RED GRANDIS 1"'},
    {code : 'CEO2', description : 'CEDRO ODORATA 2"'},
    {code : 'ENA1', description : 'ENCINO AMERICANO 1"'},
    {code : 'ENA1B', description :  'ENCINO AMERICANO 1 1/2"'},
    {code : 'ENA2', description : 'ENCINO AMERICANO 2"'},
    {code : 'MAP1', description : 'MAPLE 1"'},
    {code : 'MOR1', description : 'MOHENA ROSADA 1"'},
    {code : 'NOA1', description : 'NOGAL AMERICANO 1"'},
    {code : 'TOR1', description : 'TORNILLO (TEKA SUD) 1"'},
    {code : 'TOR1B', description :  'TORNILLO (TEKA SUD) 1 1/2"'},
    {code : 'TOR2', description : 'TORNILLO (TEKA SUD) 2"'},
    {code : 'BAL1', description : 'BALSAMO 1"'},
    {code : 'CAT1', description : 'CATALOX 1"'},
    {code : 'CAT1B', description :  'CATALOX 1 1/2"'},
    {code : 'CHE1', description : 'CHECHEN 1"'},
    {code : 'MAC1', description : 'MACHICHE 1"'},
    {code : 'MAC1B', description :  'MACHICHE 1 1/2"'},
    {code : 'MAC2', description : 'MACHICHE 2"'},
    {code : 'PAR1', description : 'GUANACASTLE (PAROTA) 1"'},
    {code : 'PAR1B', description :  'GUANACASTLE (PAROTA) 1 1/2"'},
    {code : 'PAR2', description : 'GUANACASTLE (PAROTA) 2"'},
    {code : 'PUC1', description : 'PUCTE 1"'},
    {code : 'PUC1B', description :  'PUCTE 1 1/2"'},
    {code : 'PUC2', description : 'PUCTE 2"'},
    {code : 'TZA1', description : 'TZALAM 1"'},
    {code : 'TZA1B', description :  'TZALAM 1 1/2"'},
    {code : 'TZA2', description : 'TZALAM 2"'},
    {code : 'ZAP1', description : 'ZAPOTE 1"'},
    {code : 'CEN1', description : 'CEDRO NACIONAL 1"'},
    {code : 'CEN1B', description :  'CEDRO NACIONAL 1 1/2"'},
    {code : 'CEO1', description : 'CEDRO ODORATA 1"'},
    {code : 'CEO1B', description :  'CEDRO ODORATA 1 1/2"'},
    {code : 'CEO2', description : 'CEDRO ODORATA 2"'},
    {code : 'CER1B', description :  'CEDRO REAL 1 1/2"'},
    {code : 'CER2', description : 'CEDRO REAL 2"'},
    {code : 'CUH1', description : 'CUMAHUAY 1"'},
    {code : 'CUM1', description : 'CUMARU 1"'},
    {code : 'HAY1', description : 'HAYA 1"'},
    {code : 'HAY1B', description :  'HAYA 1 1/2"'},
    {code : 'JEQ1', description : 'JEQUITIBA 1"'},
    {code : 'JEQ1B', description :  'JEQUITIBA 1 1/2"'},
    {code : 'JEQ2', description : 'JEQUITIBA 2"'},
    {code : 'NOS1', description : 'NOGAL SUDAMERICANO 1"'},
    {code : 'REQ1', description : 'REQUIA 1"'}
];
